import { ChevronDown } from 'lucide-react';
import { Reveal } from './reveal';

const FAQS = [
  {
    q: 'Which file types are supported?',
    a: 'PDF Chat accepts text-based PDF files. Scanned PDFs without a text layer cannot be read yet.',
  },
  {
    q: 'What is the file size limit?',
    a: 'Each PDF can be up to 20 MB. You can upload several files into the same chat.',
  },
  {
    q: 'Can the AI be wrong?',
    a: 'Yes. Answers are generated by a language model and can contain mistakes. In PDF mode, check the cited pages, and verify anything important.',
  },
  {
    q: 'How are YouTube lectures chosen?',
    a: 'We query the YouTube Data API for real videos matching your topic and filters. The AI only ranks and annotates those results; it never invents links.',
  },
  {
    q: 'What happens to my data?',
    a: 'Chat history and playlists are stored in your browser. Uploaded PDFs are processed in server memory for retrieval and are not permanently stored.',
  },
  {
    q: 'Is it free?',
    a: 'Yes, it is free to use during this early version. Usage is rate limited to keep the service available for everyone.',
  },
];

export function Faq() {
  return (
    <section id="faq" className="scroll-mt-20 px-4 py-24 sm:px-6">
      <div className="mx-auto flex max-w-3xl flex-col gap-10">
        <Reveal className="flex flex-col gap-3">
          <p className="hud text-accent">Signals received</p>
          <h2 className="text-gold font-display text-3xl font-semibold sm:text-5xl">FAQ</h2>
        </Reveal>
        <Reveal className="flex flex-col gap-2">
          {FAQS.map((f) => (
            <details key={f.q} className="glass group rounded-xl open:border-accent/40">
              <summary className="flex cursor-pointer list-none items-center justify-between gap-4 rounded-xl px-5 py-4 font-medium focus-visible:outline-2 focus-visible:outline-accent [&::-webkit-details-marker]:hidden">
                {f.q}
                <ChevronDown
                  className="size-4 shrink-0 text-muted transition-transform group-open:rotate-180"
                  aria-hidden="true"
                />
              </summary>
              <p className="px-5 pb-5 leading-relaxed text-muted">{f.a}</p>
            </details>
          ))}
        </Reveal>
      </div>
    </section>
  );
}
